#!/bin/bash
base_directory=$(realpath $(dirname "$BASH_SOURCE")/..)

mkdir -p ${base_directory}/install/share || exit 1
tar xvf \
  ${base_directory}/src/deps/ORB_SLAM3/Vocabulary/ORBvoc.txt.tar.gz \
  -C ${base_directory}/install/share || exit 1

docker build $base_directory -f $base_directory/Dockerfile.app \
    --tag orbslam3-docker-app
