#!/bin/bash
base_directory=$(realpath $(dirname "$BASH_SOURCE")/..)

docker build $base_directory -f $base_directory/Dockerfile.deps \
    --tag orbslam3-docker-deps

mkdir -p install || exit 1
mkdir -p build/pangolin || exit 1
mkdir -p build/orbslam3 || exit 1

docker run --rm -it \
    -v $base_directory/src/deps/Pangolin:/Pangolin \
    -v $base_directory/build/pangolin:/build \
    -v $base_directory/install:/usr/local \
    orbslam3-docker-deps \
    bash -c "\
        cmake -H/Pangolin -B/build \
          -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local \
        && cmake --build /build --target install -- -j8 \
    "

docker run --rm -it \
    -v $base_directory/src/deps/ORB_SLAM3:/ORB_SLAM3 \
    -v $base_directory/build/orbslam3:/build \
    -v $base_directory/install:/usr/local \
    orbslam3-docker-deps \
    bash -c "\
        cmake -H/ORB_SLAM3/Thirdparty/DBoW2 -B/build/DBoW2 \
          -DCMAKE_BUILD_TYPE=Release \
        && cmake --build /build/DBoW2 -- -j8 \
        && cp /ORB_SLAM3/Thirdparty/DBoW2/lib/libDBoW2.so /usr/local/lib/ \
        && mkdir -p /usr/local/include/Thirdparty/DBoW2 \
        && cp -r /ORB_SLAM3/Thirdparty/DBoW2/DBoW2 \
          /usr/local/include/Thirdparty/DBoW2/ \
        && cp -r /ORB_SLAM3/Thirdparty/DBoW2/DUtils \
          /usr/local/include/Thirdparty/DBoW2/ \
    "

docker run --rm -it \
    -v $base_directory/src/deps/ORB_SLAM3:/ORB_SLAM3 \
    -v $base_directory/build/orbslam3:/build \
    -v $base_directory/install:/usr/local \
    orbslam3-docker-deps \
    bash -c "\
        cmake -H/ORB_SLAM3/Thirdparty/g2o -B/build/g2o \
          -DCMAKE_BUILD_TYPE=Release \
        && cmake --build /build/g2o -- -j8 \
        && cp /ORB_SLAM3/Thirdparty/g2o/lib/libg2o.so /usr/local/lib/ \
        && mkdir -p /usr/local/include/Thirdparty/g2o \
        && cp -r /ORB_SLAM3/Thirdparty/g2o/g2o \
          /usr/local/include/Thirdparty/g2o/ \
        && cp /ORB_SLAM3/Thirdparty/g2o/config.h \
          /usr/local/include/Thirdparty/g2o/ \
    "

docker run --rm -it \
    -v $base_directory/src/deps/ORB_SLAM3:/ORB_SLAM3 \
    -v $base_directory/build/orbslam3:/build \
    -v $base_directory/install:/usr/local \
    orbslam3-docker-deps \
    bash -c "\
        cmake -H/ORB_SLAM3/Thirdparty/Sophus -B/build/Sophus \
          -DCMAKE_BUILD_TYPE=Release \
        && cmake --build /build/Sophus -- -j8 \
        && mkdir -p /usr/local/include/Thirdparty/Sophus \
        && cp -r /ORB_SLAM3/Thirdparty/Sophus/sophus \
          /usr/local/include/Thirdparty/Sophus/ \
    "

docker run --rm -it \
    -v $base_directory/src/deps/ORB_SLAM3:/ORB_SLAM3 \
    -v $base_directory/build/orbslam3:/build \
    -v $base_directory/install:/usr/local \
    orbslam3-docker-deps \
    bash -c "\
        cmake -H/ORB_SLAM3 -B/build/orbslam3 \
          -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local \
        && cmake --build /build/orbslam3 -- -j8 \
        && cp /ORB_SLAM3/lib/libORB_SLAM3.so /usr/local/lib/ \
        && cp -r /ORB_SLAM3/include/* /usr/local/include/ \
    "
