#!/bin/bash
base_directory=$(realpath $(dirname "$BASH_SOURCE")/..)

docker build $base_directory -f $base_directory/Dockerfile.build \
    --tag orbslam3-docker-build

catkin_root=${base_directory}/src/catkin
package_root=${catkin_root}/src/orbslam3_docker_ros
docker run --rm -it \
    -v ${package_root}:${package_root} \
    -v ${catkin_root}/build:${catkin_root}/build \
    -v ${catkin_root}/devel:${catkin_root}/devel \
    -v ${catkin_root}/install:${catkin_root}/install \
    -v ${base_directory}/install:/usr/local \
    -w ${catkin_root} \
    orbslam3-docker-build \
    bash -c " \
        catkin_make \
        -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=yes \
        install \
    "
